sudo: false # route your build to the container-based infrastructure for a faster build
language: ruby
rvm:
- 2.5.1

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

cache:
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer # https://github.com/gjtorikian/html-proofer/issues/381

before_script:
 - chmod +x ./ci/*
 - gem --version
 - gem install bundler
script:
- "./ci/build.sh"
- "./ci/deploy.sh"

addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors
